_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 3

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null

# Uncomment for 16-bit mixed floating-point precision (2x faster training)
# https://pytorch-lightning.readthedocs.io/en/latest/guides/speed.html#mixed-precision-16-bit-training
# https://github.com/huggingface/transformers/tree/master/examples/pytorch/text-classification#mixed-precision-training
# precision: 16