# output paths for hydra logs
run:
    # dir: logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: logs/${exp_name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
    dir: logs/${exp_name}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
    

defaults:
  # enable color logging
  - override hydra_logging: colorlog
  - override job_logging: colorlog