model_summary:
  _target_: pytorch_lightning.callbacks.ModelSummary
  max_depth: 1

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step