model_summary:
  _target_: pytorch_lightning.callbacks.ModelSummary
  max_depth: 1

# Cool progress bar in your console
rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

# Logs current learning rate once in a while
lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step