_target_: src.datamodules.glue_datamodule.GlueDataModule

max_seq_length: 128
tokenizer_name: ${model_name}
batch_size: 32
task_name: ${task.task_name}
cache_dir: ${work_dir}/cache
overwrite_cache: False
